name: Run Tests

on:
  push:
    branches:
      - main      # or any branch you want to run tests on
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # This sets up the environment to run the tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out the code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assumes you have a requirements.txt

      - name: Run tests
        run: |
          pytest .  # Runs pytest to execute tests